dist: trusty
sudo: required
language: python
cache: pip

python:
  - "3.5"
  - "3.5-dev"
  - "3.6"
  - "3.6-dev"

install:
  # install LXD
  - sudo add-apt-repository -y ppa:ubuntu-lxc/stable
  - sudo apt update
  - sudo apt-get install -y lxc lxd
  # create storage pool
  - sudo lxc storage create pool1 dir
  # create profile
  - sudo lxc profile copy default piper-ci
  - sudo lxc profile set piper-ci security.privileged true
  - sudo lxc profile device add piper-ci eth0 nic nictype=bridged parent=lxcbr0 name=eth0
  - sudo lxc profile device add piper-ci root disk pool=pool1 path=/
  - sudo lxc profile show piper-ci
  # copy image
  - "sudo lxc image copy images:alpine/3.5 local: --copy-aliases"
  - sudo lxc image list
  # setup LXD
  - sudo lxc config set core.https_address [::]
  - openssl genrsa 2048 > client.key
  - openssl req -new -x509 -nodes -sha1 -days 365 -key client.key -out client.crt -subj "/C=CZ/ST=Czech Republic/L=Prague/O=TEST/OU=IT Department/CN=ssl.raymii.org"
  - sudo lxc config trust add client.crt
  - mkdir ~/.config/lxc-client
  - mv client.* ~/.config/lxc-client/.
  # python deps
  - pip install -r requirements.txt
  # remove after pylxd version on pipy > 2.2.3
  - pip install git+https://github.com/lxc/pylxd.git

script:
  - python setup.py test
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then flake8; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then mypy piper_lxd/run.py; fi

after_success:
  - coveralls
