dist: trusty
language: python
cache: pip
sudo: false

python:
  - "3.5"
  - "3.6"

env:
  - TOXENV=mypy
  - TOXENV=pep8

install:
  - pip install tox

script:
  - tox

jobs:
  include:
    - &test-lxd
      sudo: required
      env: TOXENV=py,coveralls
      python: "3.5"
      stage: LXD
      before_install: bash setup_lxd_ubuntu.sh
    - <<: *test-lxd
      python: "3.6"
