dist: trusty
language: python
cache: pip
sudo: false

python:
  - "3.5"
  - "3.6"

env:
  - TOXENV=mypy
  - TOXENV=pep8

install:
  - pip install tox

script:
  - tox

jobs:
  include:
    - &test-lxd
      sudo: required
      env: TOXENV=py,coveralls
      python: "3.5"
      stage: LXD
      before_install:
        - sudo groupadd --system lxd
        - sudo usermod -a -G lxd $USER
        - sudo apt-get update -qq
        - sudo apt-get --yes install snapd
        - sudo snap install lxd
        - sudo lxd waitready
        - printf 'n\ny\ndefault\ndir\nn\ny\nlxdbr0\nauto\nauto\ny\nall\n\ny\nn\n' | sudo lxd init
        - sudo lxd.lxc profile copy default piper-ci
        - sudo lxd.lxc profile set piper-ci security.privileged true
        - "sudo lxd.lxc image copy images:alpine/3.5 local: --copy-aliases"
        - openssl genrsa 2048 > client.key
        - openssl req -new -x509 -nodes -sha1 -days 365 -key client.key -out client.crt -subj "/C=CZ/ST=Czech Republic/L=Prague/O=TEST/OU=IT Department/CN=ssl.raymii.org"
        - sudo lxd.lxc config trust add client.crt
        - mkdir ~/.config/lxc-client
        - mv client.* ~/.config/lxc-client/.
    - <<: *test-lxd
      python: "3.6"
