type: map
mapping:
  lxd:
    type: map
    mapping:
      profiles:
        type: seq
        sequence:
          - type: str
      endpoint:
        type: str
        required: yes
      cert:
        type: str
        required: yes
      key:
        type: str
        required: yes
      verify:
        type: bool
  runner:
    type: map
    mapping:
      token:
        type: str
        required: yes
      interval:
        type: int
        range:
          min: 1
      instances:
        type: int
        range:
          min: 1
      endpoint:
        type: str
        required: yes
  logging:
    type: map
    allowempty: yes

